"""
Theme Merger

Deep-merges a Vega-Lite config dict (theme) into a compiled spec.
The theme is applied as the `config` property.

Phase 1: theme is a static JSON file (manually authored).
Phase 5: theme is auto-generated by Figma -> Style Dictionary pipeline.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

DEFAULT_THEME_PATH = Path(__file__).parent / "default_theme.json"


def load_default_theme() -> dict:
    """Load the built-in default theme."""
    return json.loads(DEFAULT_THEME_PATH.read_text())


def merge_theme(spec: dict, theme: dict | None = None) -> dict:
    """
    Merge theme config into a Vega-Lite spec.
    Theme becomes spec["config"]. Spec-level config (if any) wins over theme.
    """
    if theme is None:
        theme = load_default_theme()

    result = copy.deepcopy(spec)
    existing_config = result.pop("config", {})

    # Theme is the base, spec-level config overrides
    merged_config = {**theme, **existing_config}
    result["config"] = merged_config

    return result
