"""
Theme Merger

Deep-merges a Vega-Lite config dict (theme) into a compiled spec.
The theme is applied as the `config` property.

Phase 2: theme is a structured YAML file (chart + layout sections).
Phase 5: theme is auto-generated by Figma -> Style Dictionary pipeline.
"""

from __future__ import annotations

import copy
from pathlib import Path

import yaml

from src.theme.theme_schema import ThemeSpec

DEFAULT_THEME_PATH = Path(__file__).parent / "default_theme.yaml"


def load_theme(path: Path | None = None) -> ThemeSpec:
    """
    Load a theme YAML file and return a validated ThemeSpec.

    If no path is given, loads the built-in default_theme.yaml.
    Resolves preset color references (e.g. "text.primary" → "#1a1a1a").

    Returns:
        ThemeSpec with all preset colors resolved to hex values.
    """
    theme_path = path if path is not None else DEFAULT_THEME_PATH
    data = yaml.safe_load(theme_path.read_text())
    theme = ThemeSpec(**(data or {}))
    return _resolve_preset_colors(theme)


def _resolve_preset_colors(theme: ThemeSpec) -> ThemeSpec:
    """
    Resolve preset color references like "text.primary" to actual hex values.

    Supports dot-notation lookups into layout.text:
      "text.primary"   → theme.layout.text.primary
      "text.secondary" → theme.layout.text.secondary
      "text.tertiary"  → theme.layout.text.tertiary

    Values that are already hex colors (start with "#") are left unchanged.
    Unknown references raise ValueError.

    Returns:
        A new ThemeSpec with all preset colors resolved.
    """
    resolved_presets = {}
    for name, preset in theme.layout.presets.items():
        if preset.color.startswith("#"):
            resolved_presets[name] = preset
        elif preset.color.startswith("text."):
            key = preset.color.split(".")[1]
            resolved_color = getattr(theme.layout.text, key, None)
            if resolved_color is None:
                raise ValueError(f"Unknown color reference: {preset.color}")
            resolved_presets[name] = preset.model_copy(update={"color": resolved_color})
        else:
            raise ValueError(f"Unknown color reference: {preset.color}")

    new_layout = theme.layout.model_copy(update={"presets": resolved_presets})
    return theme.model_copy(update={"layout": new_layout})


def merge_theme(spec: dict, theme: dict | ThemeSpec | None = None) -> dict:
    """
    Merge theme config into a Vega-Lite spec.
    Theme becomes spec["config"]. Spec-level config (if any) wins over theme.

    Accepts:
    - ThemeSpec: extracts theme.chart as a dict via model_dump()
    - dict with "chart" key: treats it as new-format, extracts ["chart"]
    - dict without "chart" key: treats as flat VL config dict (e.g. from tests)
    - None: loads default theme via load_theme()

    Returns:
        Deep copy of spec with config merged.
    """
    if theme is None:
        theme_obj = load_theme()
        vl_config = theme_obj.chart.model_dump()
    elif isinstance(theme, ThemeSpec):
        vl_config = theme.chart.model_dump()
    elif isinstance(theme, dict) and "chart" in theme:
        vl_config = theme["chart"]
    else:
        vl_config = theme  # legacy flat dict path

    result = copy.deepcopy(spec)
    existing_config = result.pop("config", {})

    # Theme is the base, spec-level config overrides
    merged_config = {**vl_config, **existing_config}
    result["config"] = merged_config

    return result
